version: "3"
services:
  db:
    image: postgres:14-alpine
    container_name: shortlinkdb
    volumes:
      - ".data/db:/var/lib/postgresql/data"
    env_file:
      - db.env
    environment:
      - PGDATA:/var/lib/postgresql/data/pgdata
